### ISSUE TITLE
You can't use the zip as it is

### ISSUE THREAD

**Issue by Miralyn** [stupidpupil/voicepack_template#2]
So, after comparing contents of default templates and this one, I noticed that the content of this one is packed inside the folder. It causes it to not appear as the ModBuddy template.

**Comment by stupidpupil** [comment]
Hmm, that's odd! Thanks for raising this, will look into it and get it fixed.

**Comment by stupidpupil** [comment]
I've created a new release that should fix this - apologies for taking so long to get around to this.

(I still need to fix the build script, but this isn't very important really.)

**Comment by ChrGriffin** [comment]
Hi! Dropping in to say this is still an issue. Glad this issue was here actually, helped me figure out why it wasn't working.

**Comment by stupidpupil** [comment]
Hmm - any more detail you can give? (I'm afraid it's been a long while since I touched any of this stuff, but I'd like to fix it if I can!)

**Comment by ChrGriffin** [comment]
It's a very simple issue, really!

the downloadable ZIP file on the releases page has a top-level directory called `VoicePackWithRobojumperScript`, which then contains the template files. In order for ModBuddy to recognize the template, those files actually need to be at the top level, if that makes sense.

**Comment by s204475** [comment]
So for anyone still struggling with this, just unpack the file zip and then pack the inside of the folder into a new zip that does not have the top folder. Hopefully the attached screenshots show this.

<img width="1861" height="887" alt="Image" src="https://github.com/user-attachments/assets/f3fce685-e7fe-4232-bc49-0f139fcde6f0" />

<img width="1962" height="891" alt="Image" src="https://github.com/user-attachments/assets/3c011dcc-f893-4fc2-aa7b-cabc2900fd7b" />
